# Generated by Django 3.1.4 on 2020-12-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_coursestream_1_coursetype_1'),
        ('office_administrator', '0002_auto_20201231_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_admin.coursestream'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_admin.coursetype'),
        ),
    ]
