# Generated by Django 3.1.4 on 2021-01-14 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college_owners', '0002_collegeowner_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeowner',
            name='profile_photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
